# xplat.yaml - Package manifest for xplat ecosystem
apiVersion: xplat/v1
kind: Package

name: plat-tinypio
version: main
description: PIO assembly validator powered by TinyGo's pio library
author: joeblew999
license: MIT
language: go

upstream:
  repo: https://github.com/tinygo-org/pio
  ref: main

binary:
  name: tinypio
  source:
    go: github.com/joeblew999/plat-tinypio/cmd/tinypio

processes:
  tinypio:
    command: task run
    port: 8090
    health_path: /health
    dev_mode: true  # Hot reload: watches files and auto-rebuilds
    readiness:
      initial_delay: 3
      period: 5
